services:
  finservice:
    container_name: finservice-service-container
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    restart: unless-stopped
    volumes:
      - ~/data:/app/data